import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const kanit = Kanit({
  subsets: ["thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className}`}>
        {children}
        <div className="text-center text-white mt-20 font-bold bg-green-800">
          <hr className="w-2xl mx-auto " />
          Create by Satjatum
          <br />
          Copyright &copy; 2025
        </div>
      </body>
    </html>
  );
}
